version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(deps-dev)
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
